image: node:20

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - www

pages:
  stage: deploy
  pages: true
  script:
    - mv www public
  artifacts:
    paths:
      - public
  only:
    - main
